### ISSUE TITLE
请教一下使用说明的运行容器命令运行后没有反应是怎么回事呀

### ISSUE THREAD

**Issue by wangxin1992** [aak1247/rtsp2hls#4]
请教一下按使用说明运行容器命令运行后没有反应是怎么回事呀。浏览器登录http://localhost:3001/不存在

 ffmpeg -rtsp_transport tcp -i 'rtsp://favicon.ico' -force_key_frames "expr:gte(t,n_forced*2)" -an -c:v libx264 -strict -2 -crf 25 -f hls -hls_flags delete_segments -hls_segment_filename '/app/dist/src/../rtsp_temp/favicon-ico/favicon-ico%03d.ts' '/app/dist/src/../rtsp_temp/favicon-ico/index.m3u8'
waiting for index.m3u8 to be created

这个从哪里配置呀

**Comment by aak1247** [comment]
这个服务是用来做转换的：将rtsp流转换为hls流，所以需要现有一个rtsp流地址，比如：rtsp://1@2:xxx.bbb，然后通过服务进行转换，访问http://localhost:3001/rtsp://1@2:xxx.bbb就可以拿到rtsp流对应的hls流

**Comment by aak1247** [comment]
还不支持配置转流的命令，如果一定要配的话，可以改src下的httpRouter里的转流逻辑。是有什么特殊需要嘛？

**Comment by wangxin1992** [comment]
那行我知道了，我以为上面那个打印信息是配置文件呢，没有啥要求，这样就挺好，我是看文档没看明白，谢谢啦 ，我试试效果

**Comment by wangxin1992** [comment]
docker容器启动很慢是怎么回事呀

**Comment by wangxin1992** [comment]
使用dockerfile自己构建后启动后容器就是exited状态

**Comment by wangxin1992** [comment]
最后的结论时自己构建的运行不了，使用readme的命令可以运行，但是浏览器播放还是有错误，
我通过浏览器和ffplay命令都试过了，不能播放，请问可能是咋回事呢

流地址是这个：
http://localhost:3001/rtsp://admin:dixin_Admin123@192.168.96.224/Stream1


2023-10-09T01:46:51.858018835Z   configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libmp3lame --enable-librtmp --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-x11grab --disable-stripping --disable-static --enable-vaapi --enable-libopus --disable-debug
2023-10-09T01:46:51.858043775Z   libavutil      55. 34.101 / 55. 34.101
2023-10-09T01:46:51.858066676Z   libavcodec     57. 64.101 / 57. 64.101
2023-10-09T01:46:51.858123788Z   libavformat    57. 56.101 / 57. 56.101
2023-10-09T01:46:51.858242448Z   libavdevice    57.  1.100 / 57.  1.100
2023-10-09T01:46:51.858412527Z   libavfilter     6. 65.100 /  6. 65.100
2023-10-09T01:46:51.858521979Z   libavresample   3.  1.  0 /  3.  1.  0
2023-10-09T01:46:51.858549865Z   libswscale      4.  2.100 /  4.  2.100
2023-10-09T01:46:51.858573967Z   libswresample   2.  3.100 /  2.  3.100
2023-10-09T01:46:51.858598175Z   libpostproc    54.  1.100 / 54.  1.100
2023-10-09T01:46:51.858621206Z [tcp @ 0x7f4744aa2940] Port missing in uri
2023-10-09T01:46:51.858646392Z rtsp://rtsp://admin:dixin_Admin123@192.168.96.224/Stream1: Invalid argument
2023-10-09T01:47:00.662615099Z   <-- GET /rtsp://admin:dixin_Admin123@192.168.96.224/Stream1
2023-10-09T01:47:00.662682219Z url: rtsp://admin:dixin_Admin123@192.168.96.224/Stream1
2023-10-09T01:47:00.662716274Z path: rtsp://admin:dixin_Admin123@192.168.96.224/Stream1
2023-10-09T01:47:00.662748373Z m3u8 request received, source: rtsp://admin:dixin_Admin123@192.168.96.224/Stream1
2023-10-09T01:47:00.662780274Z no targetEntry found for source: rtsp://admin:dixin_Admin123@192.168.96.224/Stream1
2023-10-09T01:47:00.663145663Z transcode with cmd:  ffmpeg -rtsp_transport tcp -i 'rtsp://rtsp://admin:dixin_Admin123@192.168.96.224/Stream1' -force_key_frames "expr:gte(t,n_forced*2)" -an -c:v libx264 -strict -2 -crf 25 -f hls -hls_flags delete_segments -hls_segment_filename '/app/dist/src/../rtsp_temp/rtsp---admin-dixin_Admin123@192-168-96-224-Stream1/rtsp---admin-dixin_Admin123@192-168-96-224-Stream1%03d.ts' '/app/dist/src/../rtsp_temp/rtsp---admin-dixin_Admin123@192-168-96-224-Stream1/index.m3u8'
2023-10-09T01:47:00.665342811Z waiting for index.m3u8 to be created

09T01:47:00.692524482Z 执行出错: Error: Command failed: ffmpeg -rtsp_transport tcp -i 'rtsp://rtsp://admin:dixin_Admin123@192.168.96.224/Stream1' -force_key_frames "expr:gte(t,n_forced*2)" -an -c:v libx264 -strict -2 -crf 25 -f hls -hls_flags delete_segments -hls_segment_filename '/app/dist/src/../rtsp_temp/rtsp---admin-dixin_Admin123@192-168-96-224-Stream1/rtsp---admin-dixin_Admin123@192-168-96-224-Stream1%03d.ts' '/app/dist/src/../rtsp_temp/rtsp---admin-dixin_Admin123@192-168-96-224-Stream1/index.m3u8'
2023-10-09T01:47:00.692685986Z ffmpeg version 3.2.9 Copyright (c) 2000-2017 the FFmpeg developers
2023-10-09T01:47:00.692761459Z   built with gcc 6.3.0 (Alpine 6.3.0)
2023-10-09T01:47:00.692839343Z   configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libmp3lame --enable-librtmp --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-x11grab --disable-stripping --disable-static --enable-vaapi --enable-libopus --disable-debug
2023-10-09T01:47:00.692878204Z   libavutil      55. 34.101 / 55. 34.101
2023-10-09T01:47:00.692910344Z   libavcodec     57. 64.101 / 57. 64.101
2023-10-09T01:47:00.692941483Z   libavformat    57. 56.101 / 57. 56.101
2023-10-09T01:47:00.692972149Z   libavdevice    57.  1.100 / 57.  1.100
2023-10-09T01:47:00.693001250Z   libavfilter     6. 65.100 /  6. 65.100
2023-10-09T01:47:00.693028951Z   libavresample   3.  1.  0 /  3.  1.  0
2023-10-09T01:47:00.693090627Z   libswscale      4.  2.100 /  4.  2.100
2023-10-09T01:47:00.693119779Z   libswresample   2.  3.100 /  2.  3.100
2023-10-09T01:47:00.693147356Z   libpostproc    54.  1.100 / 54.  1.100
2023-10-09T01:47:00.693175129Z [tcp @ 0x7f7140ee5940] Port missing in uri
2023-10-09T01:47:00.693202697Z rtsp://rtsp://admin:dixin_Admin123@192.168.96.224/Stream1: Invalid argument
2023-10-09T01:47:11.852620320Z timeout
2023-10-09T01:47:11.853057120Z   xxx GET /rtsp://admin:dixin_Admin123@192.168.96.224/Stream1 500 20s -
2023-10-09T01:47:11.854567030Z   InternalServerError: timeout
2023-10-09T01:47:11.854784944Z       at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
2023-10-09T01:47:11.854913788Z       at serve (/app/src/httpRouter.ts:119:18)
2023-10-09T01:47:11.855033063Z       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-10-09T01:47:11.855148445Z       at cors (/app/node_modules/koa2-cors/dist/index.js:36:14)
2023-10-09T01:47:11.855262417Z       at logger (/app/node_modules/koa-logger/index.js:67:7)
2023-10-09T01:47:11.855378315Z error: InternalServerError: timeout
2023-10-09T01:47:11.855491854Z     at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
2023-10-09T01:47:11.855634493Z     at serve (/app/src/httpRouter.ts:119:18)
2023-10-09T01:47:11.855876955Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-10-09T01:47:11.856157831Z     at cors (/app/node_modules/koa2-cors/dist/index.js:36:14)
2023-10-09T01:47:11.856368981Z     at logger (/app/node_modules/koa-logger/index.js:67:7)
2023-10-09T01:47:11.965105491Z   <-- GET /favicon.ico
2023-10-09T01:47:11.965323499Z url: favicon.ico
2023-10-09T01:47:11.965366777Z path: favicon.ico
2023-10-09T01:47:11.965427318Z m3u8 request received, source: favicon.ico
2023-10-09T01:47:11.965452374Z no targetEntry found for source: favicon.ico
2023-10-09T01:47:11.965667785Z transcode with cmd:  ffmpeg -rtsp_transport tcp -i 'rtsp://favicon.ico' -force_key_frames "expr:gte(t,n_forced*2)" -an -c:v libx264 -strict -2 -crf 25 -f hls -hls_flags delete_segments -hls_segment_filename '/app/dist/src/../rtsp_temp/favicon-ico/favicon-ico%03d.ts' '/app/dist/src/../rtsp_temp/favicon-ico/index.m3u8'
2023-10-09T01:47:11.967491589Z waiting for index.m3u8 to be created
2023-10-09T01:47:11.997655185Z 执行出错: Error: Command failed: ffmpeg -rtsp_transport tcp -i 'rtsp://favicon.ico' -force_key_frames "expr:gte(t,n_forced*2)" -an -c:v libx264 -strict -2 -crf 25 -f hls -hls_flags delete_segments -hls_segment_filename '/app/dist/src/../rtsp_temp/favicon-ico/favicon-ico%03d.ts' '/app/dist/src/../rtsp_temp/favicon-ico/index.m3u8'
2023-10-09T01:47:11.997725466Z ffmpeg version 3.2.9 Copyright (c) 2000-2017 the FFmpeg developers
2023-10-09T01:47:11.997799710Z   built with gcc 6.3.0 (Alpine 6.3.0)
2023-10-09T01:47:11.997830575Z   configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libmp3lame --enable-librtmp --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-x11grab --disable-stripping --disable-static --enable-vaapi --enable-libopus --disable-debug
2023-10-09T01:47:11.997898489Z   libavutil      55. 34.101 / 55. 34.101
2023-10-09T01:47:11.997930686Z   libavcodec     57. 64.101 / 57. 64.101
2023-10-09T01:47:11.997954880Z   libavformat    57. 56.101 / 57. 56.101
2023-10-09T01:47:11.997978518Z   libavdevice    57.  1.100 / 57.  1.100
2023-10-09T01:47:11.998001826Z   libavfilter     6. 65.100 /  6. 65.100
2023-10-09T01:47:11.998024191Z   libavresample   3.  1.  0 /  3.  1.  0
2023-10-09T01:47:11.998045440Z   libswscale      4.  2.100 /  4.  2.100
2023-10-09T01:47:11.998066381Z   libswresample   2.  3.100 /  2.  3.100
2023-10-09T01:47:11.998087530Z   libpostproc    54.  1.100 / 54.  1.100
2023-10-09T01:47:11.998108699Z [tcp @ 0x7f2ef51c28a0] Failed to resolve hostname favicon.ico: Name does not resolve
2023-10-09T01:47:11.998129738Z rtsp://favicon.ico: I/O error
2023-10-09T01:47:20.673395022Z timeout
2023-10-09T01:47:20.673813405Z   xxx GET /rtsp://admin:dixin_Admin123@192.168.96.224/Stream1 500 20s -
2023-10-09T01:47:20.675326655Z   InternalServerError: timeout
2023-10-09T01:47:20.675633373Z       at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
2023-10-09T01:47:20.675865015Z       at serve (/app/src/httpRouter.ts:119:18)
2023-10-09T01:47:20.675903870Z       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-10-09T01:47:20.675991288Z       at cors (/app/node_modules/koa2-cors/dist/index.js:36:14)
2023-10-09T01:47:20.676025258Z       at logger (/app/node_modules/koa-logger/index.js:67:7)
2023-10-09T01:47:20.676051704Z error: InternalServerError: timeout
2023-10-09T01:47:20.676075698Z     at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
2023-10-09T01:47:20.676099390Z     at serve (/app/src/httpRouter.ts:119:18)
2023-10-09T01:47:20.676120737Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-10-09T01:47:20.676142002Z     at cors (/app/node_modules/koa2-cors/dist/index.js:36:14)
2023-10-09T01:47:20.676163482Z     at logger (/app/node_modules/koa-logger/index.js:67:7)
2023-10-09T01:47:31.496713086Z checking stream timeout
2023-10-09T01:47:31.497143066Z checking stream timeout finished, current length: 0
2023-10-09T01:47:31.979579368Z timeout
2023-10-09T01:47:31.979704207Z   xxx GET /favicon.ico 500 20s -
2023-10-09T01:47:31.980050039Z   InternalServerError: timeout
2023-10-09T01:47:31.980105596Z       at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
2023-10-09T01:47:31.980137285Z       at serve (/app/src/httpRouter.ts:119:18)
2023-10-09T01:47:31.980205536Z       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-10-09T01:47:31.980228063Z       at cors (/app/node_modules/koa2-cors/dist/index.js:36:14)
2023-10-09T01:47:31.980269839Z       at logger (/app/node_modules/koa-logger/index.js:67:7)
2023-10-09T01:47:31.980292290Z error: InternalServerError: timeout
2023-10-09T01:47:31.980314020Z     at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
2023-10-09T01:47:31.980335795Z     at serve (/app/src/httpRouter.ts:119:18)
2023-10-09T01:47:31.980357487Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-10-09T01:47:31.980383963Z     at cors (/app/node_modules/koa2-cors/dist/index.js:36:14)
2023-10-09T01:47:31.980414726Z     at logger (/app/node_modules/koa-logger/index.js:67:7)

**Comment by wangxin1992** [comment]
知道咋回事了，不能加rtsp://，查看资源占用情况，发现资源占用比较高，我的i59400F显示cpu占130%多，大致明白了如何使用谢谢

**Comment by aak1247** [comment]
感谢关注，转码确实资源占用比较大。文档已修改。docker构建的问题我稍后看看

**Comment by wangxin1992** [comment]
整体来说还是挺好的，这样使用还是挺方便的
